---
services:
  delinkify:
    build:
      context: .
      args:
        UID: ${DELINKIFY_UID:-1000}
        GID: ${DELINKIFY_GID:-1000}
    container_name: bot-delinkify
    env_file: .env
    volumes:
      - ${DELINKIFY_LOG_PATH:-./logs}:/app/logs
      - ${DELINKIFY_CACHE_PATH:-./cache}:/app/cache
      - ${DELINKIFY_MEDIA_PATH:-./media}:/app/media
      - ${DELINKIFY_COOKIE_PATH:-./cookies}:/app/cookies
    restart: unless-stopped
